spring:
  cloud:
    zookeeper:
      connect-string: 192.168.3.201:2182
      discovery:
        register: false
provider:
    ribbon:
      NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
server:
  port: 7000